[package]
name = "mp4_shuffler"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.20.0"
clap = { version = "4.5.23", features = ["derive"] }
image = "0.25.5"
mp4 = "0.14.0"
nix = "0.29.0"
rand = "0.8.5"
